[package]
name = "unscramble"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
rand = { version = "0.8" }
fasttext = "0.7"
stop-words = "0.9.0"
const_format = "0.2"
